import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [dogLink, setDogLink] = useState(
    "http://elelur.com/data_images/dog-breeds/pit-bull/pit-bull-04.jpg"
  );

  async function getPhoto() {
    try {
      // api/dog
      const response = await fetch("api/dog");
      const data = await response.json();
      console.log("data from /api/dog", data);
      setDogLink(data.dogPhotoLink);
      return data.dogPhotoLink;
    } catch (e) {
      console.log(e.message);
    }
  }

  return (
    <>
      <Head>
        <title>Greatest Dog App</title>
        <meta
          name="description"
          content="Generated by create the greatest dog CEO ever!"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.main} ${inter.className}`}>
        <h1 className={`${styles.heading}`}>Greatest Dog App Ever!</h1>
        <p className={`${styles.subheading}`}>Doggo !!</p>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <img src={dogLink} alt="" width="512px" />
          <p>I like biting kids</p>
          <button
            onClick={async function someFunctionName() {
              const data = await getPhoto();
            }}
          >
            Get Dog Photo
          </button>
        </div>
      </div>
    </>
  );
}
